version: '3.8'
services:
  mssql:
    container_name: champ.mssql
    image: mcr.microsoft.com/mssql/server:2019-latest 
    restart: always
    environment:
      - SA_PASSWORD=Tualet-2015
      - ACCEPT_EULA=Y
    volumes:
      - mssql:/var/opt/mssql
    ports:
      - 1433:1433

volumes:
  mssql:
